### PR TITLE
SVCPLAN-1702 - Add new allow_list param

### PR DESCRIPTION
**Pull request by bsper2**
Adding an allow_list param that will allow more flexible edits to sshd_config than what is currently possible with other modules like puppet-profile_allow_ssh_from_bastion

### CODE REVIEW

**Comment by bsper2** [comment]
@andylytical This has the changes you requested in https://github.com/ncsa/puppet-sshd/pull/15, it has been tested and ready for review.

**Comment by billglick** [comment]
Are you planning to add any support for ordering of multiple match blocks?

**Comment by bsper2** [comment]
> Are you planning to add any support for ordering of multiple match blocks?

Not in this pull request. I was exploring some options that would hopefully allow that in the branch `bsper2/SVCPLAN-2176/allow_new_match_configs` but the ordering didn't seem to be working, hadn't done a deep look into why yet but was wanting to at least get this part completed so Delta can get off using the old topic branch in production.

**Review by billglick — APPROVED** [review]
This looks good to me. I think it meets what @andylytical was asking for in #15 . And I like that it doesn't break any of the current parameters, etc.

I've been reviewing it in anticipation of addressing the `sshd_config_match` `position` parameter for setting ordering in a future branch.

**Pull request merged**
